# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-12 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cci', models.CharField(max_length=32)),
                ('sc', models.CharField(blank=True, max_length=32, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('scref', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpe', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('os', models.CharField(blank=True, max_length=256, null=True)),
                ('hardware', models.CharField(blank=True, max_length=64, null=True)),
                ('hostname', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.CharField(blank=True, max_length=128, null=True)),
                ('ip', models.CharField(blank=True, max_length=32, null=True)),
                ('mac', models.TextField(blank=True, null=True)),
                ('bios_uid', models.CharField(blank=True, max_length=164, null=True)),
                ('netbios_name', models.CharField(blank=True, max_length=64, null=True)),
                ('cpes', models.ManyToManyField(blank=True, to='poam.CPE')),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointOfContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=256)),
                ('phone', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'point_of_contact',
            },
        ),
        migrations.CreateModel(
            name='SecurityControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'security_control',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('dod_component', models.CharField(max_length=8)),
                ('dod_it_resource_number', models.CharField(max_length=32)),
                ('system_type', models.CharField(max_length=16)),
                ('point_of_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='poam.PointOfContact')),
            ],
            options={
                'db_table': 'system',
            },
        ),
        migrations.CreateModel(
            name='VulnId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln_id', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'db_table': 'vuln_id',
            },
        ),
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('mitigation', models.TextField(blank=True, null=True)),
                ('security_control', models.TextField(blank=True, null=True)),
                ('resources_required', models.CharField(blank=True, max_length=16, null=True)),
                ('scheduled_completion_date', models.DateField(blank=True, null=True)),
                ('milestone_changes', models.CharField(blank=True, max_length=16, null=True)),
                ('status', models.CharField(max_length=32)),
                ('comments', models.TextField(blank=True, null=True)),
                ('finding_details', models.TextField(blank=True, null=True)),
                ('stig_ref', models.TextField(blank=True, null=True)),
                ('raw_severity', models.CharField(blank=True, max_length=8)),
                ('mitigated_severity', models.CharField(blank=True, max_length=4, null=True)),
                ('source_identifying_date', models.DateField()),
                ('source_identifying_event', models.CharField(max_length=32)),
                ('source_identifying_tool', models.CharField(max_length=256)),
                ('check_contents', models.TextField(blank=True, null=True)),
                ('fix_text', models.TextField(blank=True, null=True)),
                ('plugin_family', models.TextField(blank=True, null=True)),
                ('plugin_output', models.TextField(blank=True, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('credentialed_scan', models.CharField(blank=True, max_length=16, null=True)),
                ('cvss_base_score', models.TextField(blank=True, null=True)),
                ('cvss_temporal_score', models.TextField(blank=True, null=True)),
                ('cvss_vector', models.TextField(blank=True, null=True)),
                ('cvss_temporal_vector', models.TextField(blank=True, null=True)),
                ('cvss3_base_score', models.TextField(blank=True, null=True)),
                ('cvss3_vector', models.TextField(blank=True, null=True)),
                ('exploit_available', models.TextField(blank=True, null=True)),
                ('cve', models.TextField(blank=True, null=True)),
                ('risk_factor', models.TextField(blank=True, null=True)),
                ('vuln_pub_date', models.TextField(blank=True, null=True)),
                ('cci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to='poam.CCI')),
                ('devices', models.ManyToManyField(to='poam.Device')),
                ('point_of_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to='poam.PointOfContact')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to='poam.System')),
                ('vuln_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to='poam.VulnId')),
            ],
            options={
                'db_table': 'weakness',
            },
        ),
        migrations.AlterUniqueTogether(
            name='securitycontrol',
            unique_together=set([('control_number', 'title')]),
        ),
        migrations.AddField(
            model_name='device',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='poam.System'),
        ),
        migrations.AddIndex(
            model_name='weakness',
            index=models.Index(fields=['vuln_id'], name='weakness_vuln_id_c7d5f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('name', 'system')]),
        ),
    ]
