# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='weakness',
            name='milestone_changes',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='weakness',
            name='mitigated_severity',
            field=models.CharField(choices=[('null', ''), ('1', 'I'), ('2', 'II'), ('3', 'III')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='weakness',
            name='mitigation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='weakness',
            name='resources_required',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='weakness',
            name='scheduled_completion_date',
            field=models.DateField(null=True),
        ),
        migrations.AddIndex(
            model_name='weakness',
            index=models.Index(fields=['vuln_id'], name='weakness_vuln_id_df0476_idx'),
        ),
    ]
