# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitycontrol',
            name='control_number',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
