# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-06 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poam', '0002_auto_20180517_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln_id', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'db_table': 'vuln_id',
            },
        ),
        migrations.RemoveIndex(
            model_name='weakness',
            name='weakness_vuln_id_df0476_idx',
        ),
        migrations.AlterField(
            model_name='weakness',
            name='vuln_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to='poam.VulnId'),
        ),
        migrations.AddIndex(
            model_name='weakness',
            index=models.Index(fields=['vuln_id'], name='weakness_vuln_id_c7d5f9_idx'),
        ),
    ]
