# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-06 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poam', '0003_auto_20180706_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weakness',
            name='source_identifying_tool',
            field=models.CharField(max_length=256),
        ),
    ]
