# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poam', '0003_auto_20180315_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpe', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='bios_uid',
            field=models.CharField(blank=True, max_length=164, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='hostname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='mac',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='netbios_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='weakness',
            name='cpe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weakness',
            name='cve',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weakness',
            name='cvss3_base_score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weakness',
            name='cvss3_vector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weakness',
            name='risk_factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weakness',
            name='vuln_pub_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securitycontrol',
            name='control_number',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='cpe',
            field=models.ManyToManyField(blank=True, to='poam.CPE'),
        ),
    ]
